version: 2
jobs:
  build:
    working_directory: ~/wd
    docker:
      - image: node:6
    steps:
      - checkout
      - run:
            name: Trigger Jobs
            command: |
              function trigger_job() {
                job_name=$1
                curl -u ${CIRCLE_API_TOKEN}: \
                  -d build_parameters[CIRCLE_JOB]=${job_name} \
                  -d revision=$CIRCLE_SHA1 \
                  https://circleci.com/api/v1.1/project/github/your_org/your_project/tree/$CIRCLE_BRANCH
              }      
              trigger_job build-node4
              trigger_job build-node6
              trigger_job build-node7

  build-node4:
       docker:
        - image: node:4
       working_directory: ~/wd
       steps:
         - run: npm version
  
  build-node6:
       docker:
        - image: node:6
       working_directory: ~/wd
       steps:
         - run: npm version
  
  build-node7:
       docker:
        - image: node:7
       working_directory: ~/wd
       steps:
         - run: npm version
