version: 2
jobs:
  build:
    docker:
      - image: node:6
    working_directory: ~/wd
    steps:
      - checkout
      - run:
          name: Trigger Jobs
          command: |
            echo $CIRCLE_API_TOKEN
            function trigger_job() {
              job_name=$1
              curl --user ${CIRCLE_API_TOKEN}: \
                --data build_parameters[CIRCLE_JOB]=$job_name \
                --data revision=$CIRCLE_SHA1 \
                https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
            }      
            trigger_job build-node4
            trigger_job build-node6
            trigger_job build-node7

  build-node-common: &common-build
    docker:
      - image: node
    working_directory: ~/wd
    environment:
      NODE_VERSION: 0
    steps:
      - run: echo "NODE_VERSION $NODE_VERSION"
      - run: npm version
      - run:
          name: Versions
          command: |
            npm version
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{ .Branch }}-node{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}
            - v1-npm-{{ .Branch }}-node{{ .Environment.NODE_VERSION }}-{{ checksum "package.json" }}
            - v1-npm-master-node{{ .Environment.NODE_VERSION }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Test
          command: npm test
      - save_cache:
          key: v1-npm-{{ .Branch }}-node{{ .Environment.NODE_VERSION }}-{{ checksum "package.json" }}
          paths:
            - node_modules

  build-node4:
    <<: *common-build
    docker:
      - image: node:4
    environment:
      - NODE_VERSION: 4
  
  build-node6:
    <<: *common-build
    docker:
      - image: node:6
    environment:
      NODE_VERSION: 6

  build-node7:
    <<: *common-build
    docker:
      - image: node:7
    environment:
      NODE_VERSION: 7
