version: 2
jobs:
  build:
    working_directory: ~/wd
    docker:
      - image: node:6
    steps:
      - checkout
      - run:
            name: Trigger Jobs
            command: |
              echo $CIRCLE_API_TOKEN
              function trigger_job() {
                job_name=$1
                curl --user ${CIRCLE_API_TOKEN}: \
                  --data build_parameters[CIRCLE_JOB]=$job_name \
                  --data revision=$CIRCLE_SHA1 \
                  https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
              }      
              trigger_job build-node4
              trigger_job build-node6
              trigger_job build-node7

  build-node-common:
       docker:
        - image: node:4
       working_directory: ~/wd
       steps: &id001
         - run: npm version

  build-node4:
       docker:
        - image: node:4
       working_directory: ~/wd
       steps: *id001
  
  build-node6:
       docker:
        - image: node:6
       working_directory: ~/wd
       steps: *id001
  
  build-node7:
       docker:
        - image: node:7
       working_directory: ~/wd
       steps: *id001
